import {
  Archive,
  Award,
  Banknote,
  Bitcoin,
  Book,
  BookOpen,
  Briefcase,
  Calendar,
  Camera,
  Car,
  CircleCheck,
  Clipboard,
  Clock,
  Cloud,
  Code,
  Cpu,
  CreditCard,
  Database,
  Disc3,
  Dumbbell,
  Feather,
  FileText,
  Film,
  Fingerprint,
  Flag,
  Folder,
  Gamepad2,
  Gift,
  Globe,
  GraduationCap,
  Heart,
  House,
  IdCard,
  Image,
  Info,
  Key,
  KeySquare,
  Landmark,
  List,
  Lock,
  LucideIcon,
  Luggage,
  Mail,
  MessageCircle,
  Monitor,
  Music,
  Package,
  PawPrint,
  Pen,
  Plane,
  Printer,
  Router,
  Server,
  Settings,
  Shield,
  ShoppingCart,
  Smartphone,
  Star,
  Stethoscope,
  StickyNote,
  Terminal,
  Trash2,
  TriangleAlert,
  Tv,
  UserRound,
  Users,
  Utensils,
  Wallet,
  Wifi,
  Wrench,
} from "lucide-react";

export interface LibraryIcon {
  /** Stable id persisted in the vault — never rename one. */
  key: string;
  label: string;
  /** Extra words the picker's search matches on. */
  keywords: readonly string[];
  Icon: LucideIcon;
}

/**
 * The built-in icon library. Every key also needs a KeePass mapping in
 * infrastructure/kdbx-icon.ts (a test enforces this). Order is display order.
 */
export const LIBRARY_ICONS: readonly LibraryIcon[] = [
  { key: "key", label: "Key", keywords: ["password", "login"], Icon: Key },
  { key: "keys", label: "Keys", keywords: ["access"], Icon: KeySquare },
  { key: "lock", label: "Lock", keywords: ["secure", "secret"], Icon: Lock },
  { key: "shield", label: "Shield", keywords: ["security", "vpn", "antivirus"], Icon: Shield },
  { key: "fingerprint", label: "Fingerprint", keywords: ["biometric", "2fa"], Icon: Fingerprint },
  { key: "star", label: "Star", keywords: ["favorite", "important"], Icon: Star },
  { key: "heart", label: "Heart", keywords: ["love", "dating"], Icon: Heart },
  { key: "flag", label: "Flag", keywords: ["marked"], Icon: Flag },
  { key: "folder", label: "Folder", keywords: ["files", "directory"], Icon: Folder },
  { key: "archive", label: "Archive", keywords: ["box", "old"], Icon: Archive },
  { key: "package", label: "Package", keywords: ["parcel", "delivery"], Icon: Package },
  { key: "document", label: "Document", keywords: ["file", "paper"], Icon: FileText },
  { key: "note", label: "Note", keywords: ["memo", "secure note"], Icon: StickyNote },
  { key: "clipboard", label: "Clipboard", keywords: ["copy"], Icon: Clipboard },
  { key: "list", label: "List", keywords: ["todo"], Icon: List },
  { key: "book", label: "Book", keywords: ["reading", "library"], Icon: Book },
  { key: "wiki", label: "Wiki", keywords: ["docs", "knowledge"], Icon: BookOpen },
  { key: "pen", label: "Pen", keywords: ["write", "sign"], Icon: Pen },
  { key: "globe", label: "Website", keywords: ["web", "internet", "world"], Icon: Globe },
  { key: "mail", label: "Email", keywords: ["inbox", "mailbox"], Icon: Mail },
  { key: "chat", label: "Chat", keywords: ["message", "messenger"], Icon: MessageCircle },
  { key: "people", label: "People", keywords: ["team", "social", "family"], Icon: Users },
  { key: "user", label: "Account", keywords: ["person", "profile"], Icon: UserRound },
  { key: "identity", label: "ID card", keywords: ["passport", "license"], Icon: IdCard },
  { key: "phone", label: "Phone", keywords: ["mobile", "sim", "pin"], Icon: Smartphone },
  { key: "home", label: "Home", keywords: ["house", "personal"], Icon: House },
  { key: "briefcase", label: "Work", keywords: ["job", "office", "business"], Icon: Briefcase },
  { key: "school", label: "School", keywords: ["education", "university"], Icon: GraduationCap },
  { key: "bank", label: "Bank", keywords: ["finance", "banking"], Icon: Landmark },
  { key: "card", label: "Credit card", keywords: ["payment", "debit"], Icon: CreditCard },
  { key: "wallet", label: "Wallet", keywords: ["money", "payment"], Icon: Wallet },
  { key: "money", label: "Money", keywords: ["cash", "salary"], Icon: Banknote },
  { key: "bitcoin", label: "Crypto", keywords: ["bitcoin", "coin", "exchange"], Icon: Bitcoin },
  { key: "cart", label: "Shopping", keywords: ["store", "shop", "cart"], Icon: ShoppingCart },
  { key: "gift", label: "Gift", keywords: ["voucher", "present"], Icon: Gift },
  { key: "luggage", label: "Luggage", keywords: ["travel", "trip", "suitcase"], Icon: Luggage },
  { key: "plane", label: "Flight", keywords: ["travel", "airline"], Icon: Plane },
  { key: "car", label: "Car", keywords: ["vehicle", "transport"], Icon: Car },
  { key: "food", label: "Food", keywords: ["restaurant", "delivery"], Icon: Utensils },
  {
    key: "health",
    label: "Health",
    keywords: ["doctor", "medical", "insurance"],
    Icon: Stethoscope,
  },
  { key: "fitness", label: "Fitness", keywords: ["gym", "sport"], Icon: Dumbbell },
  { key: "pet", label: "Pet", keywords: ["animal", "vet"], Icon: PawPrint },
  { key: "gamepad", label: "Games", keywords: ["gaming", "console"], Icon: Gamepad2 },
  { key: "music", label: "Music", keywords: ["audio", "streaming"], Icon: Music },
  { key: "film", label: "Film", keywords: ["movie", "video", "streaming"], Icon: Film },
  { key: "tv", label: "TV", keywords: ["television", "screen"], Icon: Tv },
  { key: "camera", label: "Camera", keywords: ["photo"], Icon: Camera },
  { key: "image", label: "Image", keywords: ["picture", "photo"], Icon: Image },
  { key: "disc", label: "Disc", keywords: ["cd", "license key"], Icon: Disc3 },
  { key: "calendar", label: "Calendar", keywords: ["date", "event"], Icon: Calendar },
  { key: "clock", label: "Clock", keywords: ["time"], Icon: Clock },
  { key: "monitor", label: "Computer", keywords: ["pc", "desktop"], Icon: Monitor },
  { key: "terminal", label: "Terminal", keywords: ["ssh", "shell", "console"], Icon: Terminal },
  { key: "code", label: "Code", keywords: ["developer", "api", "token"], Icon: Code },
  { key: "server", label: "Server", keywords: ["host", "hosting"], Icon: Server },
  { key: "database", label: "Database", keywords: ["sql", "db"], Icon: Database },
  { key: "cloud", label: "Cloud", keywords: ["storage", "sync"], Icon: Cloud },
  { key: "router", label: "Router", keywords: ["network", "modem"], Icon: Router },
  { key: "wifi", label: "Wi-Fi", keywords: ["wireless", "network"], Icon: Wifi },
  { key: "chip", label: "Hardware", keywords: ["cpu", "device"], Icon: Cpu },
  { key: "printer", label: "Printer", keywords: ["print"], Icon: Printer },
  { key: "settings", label: "Settings", keywords: ["config", "admin"], Icon: Settings },
  { key: "tools", label: "Tools", keywords: ["repair", "maintenance"], Icon: Wrench },
  { key: "certificate", label: "Certificate", keywords: ["award", "ssl"], Icon: Award },
  { key: "check", label: "Checked", keywords: ["done", "verified"], Icon: CircleCheck },
  { key: "info", label: "Info", keywords: ["about"], Icon: Info },
  { key: "warning", label: "Warning", keywords: ["alert", "caution"], Icon: TriangleAlert },
  { key: "trash", label: "Trash", keywords: ["delete", "old"], Icon: Trash2 },
  { key: "feather", label: "Feather", keywords: ["light", "writing"], Icon: Feather },
];

const BY_KEY = new Map(LIBRARY_ICONS.map((icon) => [icon.key, icon]));

export function findLibraryIcon(key: string): LibraryIcon | undefined {
  return BY_KEY.get(key);
}
